POST http://localhost:8000/customers
Content-Type: application/json

{
    "customerId": 1,
    "name": "shohei ohtani",
    "address": "los angeles angels"
}

###

GET http://localhost:8000/customers/1

###

PUT http://localhost:8000/customers/1
Content-Type: application/json

{
    "customerId": 1,
    "name": "shohei ohtani",
    "address": "new york yankees"
}

###

DELETE http://localhost:8000/customers/1
