POST http://localhost:8000/products
Content-Type: application/json

{
    "productId": 1,
    "name": "cap",
    "pricePerUnit": 20
}

###

GET http://localhost:8000/products/1

###

PUT http://localhost:8000/products/1
Content-Type: application/json

{
    "productId": 1,
    "name": "t-shirt",
    "pricePerUnit": 10
}

###

DELETE http://localhost:8000/products/1
